services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    environment:
      NODE_ENV: production
      PORT: 3001
      CLIENT_URL: http://localhost:5173
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "5173:80"
    restart: unless-stopped
